add_test([=[PeParser.RejectsEmptyBuffer]=]  /home/runner/work/testAgentC/testAgentC/_codeql_build_dir/bindiff_tests [==[--gtest_filter=PeParser.RejectsEmptyBuffer]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PeParser.RejectsEmptyBuffer]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/testAgentC/testAgentC/_codeql_build_dir SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PeParser.RejectsNonPeFile]=]  /home/runner/work/testAgentC/testAgentC/_codeql_build_dir/bindiff_tests [==[--gtest_filter=PeParser.RejectsNonPeFile]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PeParser.RejectsNonPeFile]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/testAgentC/testAgentC/_codeql_build_dir SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PeParser.ParsesMinimalPe32]=]  /home/runner/work/testAgentC/testAgentC/_codeql_build_dir/bindiff_tests [==[--gtest_filter=PeParser.ParsesMinimalPe32]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PeParser.ParsesMinimalPe32]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/testAgentC/testAgentC/_codeql_build_dir SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PeParser.MachineName]=]  /home/runner/work/testAgentC/testAgentC/_codeql_build_dir/bindiff_tests [==[--gtest_filter=PeParser.MachineName]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PeParser.MachineName]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/testAgentC/testAgentC/_codeql_build_dir SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PeParser.TimestampString]=]  /home/runner/work/testAgentC/testAgentC/_codeql_build_dir/bindiff_tests [==[--gtest_filter=PeParser.TimestampString]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PeParser.TimestampString]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/testAgentC/testAgentC/_codeql_build_dir SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PeParser.DetectsDifferentEntryPoints]=]  /home/runner/work/testAgentC/testAgentC/_codeql_build_dir/bindiff_tests [==[--gtest_filter=PeParser.DetectsDifferentEntryPoints]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PeParser.DetectsDifferentEntryPoints]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/testAgentC/testAgentC/_codeql_build_dir SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PeParser.ParseNonExistentFile]=]  /home/runner/work/testAgentC/testAgentC/_codeql_build_dir/bindiff_tests [==[--gtest_filter=PeParser.ParseNonExistentFile]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PeParser.ParseNonExistentFile]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/testAgentC/testAgentC/_codeql_build_dir SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PeDiff.IdenticalFilesNoChanges]=]  /home/runner/work/testAgentC/testAgentC/_codeql_build_dir/bindiff_tests [==[--gtest_filter=PeDiff.IdenticalFilesNoChanges]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PeDiff.IdenticalFilesNoChanges]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/testAgentC/testAgentC/_codeql_build_dir SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PeDiff.FileSizeChange]=]  /home/runner/work/testAgentC/testAgentC/_codeql_build_dir/bindiff_tests [==[--gtest_filter=PeDiff.FileSizeChange]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PeDiff.FileSizeChange]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/testAgentC/testAgentC/_codeql_build_dir SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PeDiff.EntryPointChange]=]  /home/runner/work/testAgentC/testAgentC/_codeql_build_dir/bindiff_tests [==[--gtest_filter=PeDiff.EntryPointChange]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PeDiff.EntryPointChange]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/testAgentC/testAgentC/_codeql_build_dir SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PeDiff.SectionAdded]=]  /home/runner/work/testAgentC/testAgentC/_codeql_build_dir/bindiff_tests [==[--gtest_filter=PeDiff.SectionAdded]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PeDiff.SectionAdded]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/testAgentC/testAgentC/_codeql_build_dir SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PeDiff.SectionRemoved]=]  /home/runner/work/testAgentC/testAgentC/_codeql_build_dir/bindiff_tests [==[--gtest_filter=PeDiff.SectionRemoved]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PeDiff.SectionRemoved]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/testAgentC/testAgentC/_codeql_build_dir SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PeDiff.ImportDllAdded]=]  /home/runner/work/testAgentC/testAgentC/_codeql_build_dir/bindiff_tests [==[--gtest_filter=PeDiff.ImportDllAdded]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PeDiff.ImportDllAdded]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/testAgentC/testAgentC/_codeql_build_dir SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PeDiff.ExportAdded]=]  /home/runner/work/testAgentC/testAgentC/_codeql_build_dir/bindiff_tests [==[--gtest_filter=PeDiff.ExportAdded]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PeDiff.ExportAdded]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/testAgentC/testAgentC/_codeql_build_dir SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PeDiff.ArchitectureChange]=]  /home/runner/work/testAgentC/testAgentC/_codeql_build_dir/bindiff_tests [==[--gtest_filter=PeDiff.ArchitectureChange]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PeDiff.ArchitectureChange]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/testAgentC/testAgentC/_codeql_build_dir SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PeDiff.InvalidOldFile]=]  /home/runner/work/testAgentC/testAgentC/_codeql_build_dir/bindiff_tests [==[--gtest_filter=PeDiff.InvalidOldFile]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PeDiff.InvalidOldFile]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/testAgentC/testAgentC/_codeql_build_dir SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PeDiff.ImportFunctionChange]=]  /home/runner/work/testAgentC/testAgentC/_codeql_build_dir/bindiff_tests [==[--gtest_filter=PeDiff.ImportFunctionChange]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PeDiff.ImportFunctionChange]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/testAgentC/testAgentC/_codeql_build_dir SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Sha256.EmptyString]=]  /home/runner/work/testAgentC/testAgentC/_codeql_build_dir/bindiff_tests [==[--gtest_filter=Sha256.EmptyString]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Sha256.EmptyString]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/testAgentC/testAgentC/_codeql_build_dir SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Sha256.HelloWorld]=]  /home/runner/work/testAgentC/testAgentC/_codeql_build_dir/bindiff_tests [==[--gtest_filter=Sha256.HelloWorld]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Sha256.HelloWorld]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/testAgentC/testAgentC/_codeql_build_dir SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Sha256.VectorOverload]=]  /home/runner/work/testAgentC/testAgentC/_codeql_build_dir/bindiff_tests [==[--gtest_filter=Sha256.VectorOverload]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Sha256.VectorOverload]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/testAgentC/testAgentC/_codeql_build_dir SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Strings.AsciiBasic]=]  /home/runner/work/testAgentC/testAgentC/_codeql_build_dir/bindiff_tests [==[--gtest_filter=Strings.AsciiBasic]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Strings.AsciiBasic]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/testAgentC/testAgentC/_codeql_build_dir SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Strings.AsciiMinLen]=]  /home/runner/work/testAgentC/testAgentC/_codeql_build_dir/bindiff_tests [==[--gtest_filter=Strings.AsciiMinLen]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Strings.AsciiMinLen]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/testAgentC/testAgentC/_codeql_build_dir SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Strings.Utf16leBasic]=]  /home/runner/work/testAgentC/testAgentC/_codeql_build_dir/bindiff_tests [==[--gtest_filter=Strings.Utf16leBasic]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Strings.Utf16leBasic]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/testAgentC/testAgentC/_codeql_build_dir SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Strings.ExtractAll]=]  /home/runner/work/testAgentC/testAgentC/_codeql_build_dir/bindiff_tests [==[--gtest_filter=Strings.ExtractAll]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Strings.ExtractAll]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/testAgentC/testAgentC/_codeql_build_dir SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Strings.EmptyInput]=]  /home/runner/work/testAgentC/testAgentC/_codeql_build_dir/bindiff_tests [==[--gtest_filter=Strings.EmptyInput]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Strings.EmptyInput]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/testAgentC/testAgentC/_codeql_build_dir SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  bindiff_tests_TESTS PeParser.RejectsEmptyBuffer PeParser.RejectsNonPeFile PeParser.ParsesMinimalPe32 PeParser.MachineName PeParser.TimestampString PeParser.DetectsDifferentEntryPoints PeParser.ParseNonExistentFile PeDiff.IdenticalFilesNoChanges PeDiff.FileSizeChange PeDiff.EntryPointChange PeDiff.SectionAdded PeDiff.SectionRemoved PeDiff.ImportDllAdded PeDiff.ExportAdded PeDiff.ArchitectureChange PeDiff.InvalidOldFile PeDiff.ImportFunctionChange Sha256.EmptyString Sha256.HelloWorld Sha256.VectorOverload Strings.AsciiBasic Strings.AsciiMinLen Strings.Utf16leBasic Strings.ExtractAll Strings.EmptyInput)
